objectives:
  "4x":
    magnification: 4
    fov_mm:
      width: 3.22
      height: 3.22

    switch:
      enabled: true
      mode: motor_manager
      objective_target_pos: 166347
      focus_target_pos: -1923201 #对应细准焦螺旋，粗准焦螺旋不应移动

      # 物镜/调焦电机运动参数
      objective_profile_vel: 100000
      objective_profile_acc: 100000
      objective_profile_dec: 100000

      focus_profile_vel: 100000
      focus_profile_acc: 100000
      focus_profile_dec: 100000

  "10x":
    magnification: 10
    fov_mm:
      width: 1.31
      height: 1.31

    switch:
      enabled: true
      mode: motor_manager
      objective_target_pos: -165903
      focus_target_pos: -2074313

      objective_profile_vel: 100000
      objective_profile_acc: 100000
      objective_profile_dec: 100000

      focus_profile_vel: 100000
      focus_profile_acc: 100000
      focus_profile_dec: 100000

state:
  enabled: true
  state_file: "C:/colony_system/data/objective_state.json"
  assume_initial: "4x"

hardware:
  modbus:
    port: "COM3"
    baudrate: 115200

  objective_axis:
    slave: 4

  focus_axis:
    slave: 3